# Generated by Django 5.0 on 2023-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
